name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # or whichever version you're using
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Run tests with JUnit
      run: mvn test --file pom.xml
